[env]
NFT_BURN_BRIDGING_PROGRAM_ID_FILE = "../../../target/deploy/nft_burn_bridging-program_id.bin"
SOLANA_EMITTER_PROGRAM_ID_FILE = "../../../target/deploy/solana_emitter-program_id.bin"
HELLO_TOKEN_PROGRAM_ID_FILE = "../../../target/deploy/hello_token-program_id.bin"
